#!/usr/bin/env python

from sys import stdin

for line in stdin:
    tokens = line.strip().split()
    if tokens[-1] == 'N':
        continue

    chromosome = tokens[0]
    start = int(tokens[1])
    end = int(tokens[1])

    reference = tokens[2]
    sample = tokens[3]
    alternate = tokens[4]
    VAF = tokens[6]
    allele = None

    if alternate.find("-") != -1:
        # deletion
        ref = reference + alternate[1:]
        alt = reference
    elif alternate.find("+") != -1:
        # insertion
        ref = reference
        alt = reference + alternate[1:]
        start = end + 1
    else:
        # substitution
        ref = reference
        alt = alternate

    identifier = "%s:%s" % (sample, VAF)
    output = [chromosome, start, ".", ref, alt, ".", ".", identifier]

    print "\t".join(map(str, output))
